# -*- coding: utf-8 -*-
"""Colour Fixing for predicted masks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIp4dohxGEppV3ouOlbvtMbaLap-9ctd
"""

#predicted mask gulo white and grey chilo,oigulaka white and black kora.


import cv2
from google.colab.patches import cv2_imshow

for p in range(1,117):

  img = cv2.imread(f'/content/predicted_mask{p}.png', cv2.IMREAD_GRAYSCALE)

  for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        pixel = img[i][j]
        if pixel >= 166: #predicted er white fully white na,tai range hlo 166 thake 255 porjonto sob gula,seigula white krbo
            img[i][j] = 255
        else:
            img[i][j] = 0

  cv2_imshow(img)
  cv2.imwrite(f'/content/{p}T.png', img)


print("Binary image saved.")