# -*- coding: utf-8 -*-
"""overlapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111fAA24mveqkLIv1JAQGwJZtB0lPqosX
"""

import cv2
from google.colab.patches import cv2_imshow
from google.colab import drive
import PIL

for p in range(1, 117):

    img1 = cv2.imread(f'/content/{p}M.png', cv2.IMREAD_GRAYSCALE) #gum
    img2 = cv2.imread(f'/content/{p}T.png', cv2.IMREAD_GRAYSCALE) #teeth

    for i in range(img2.shape[0]):  #teeth er black ke white kore daoya,and white ke black,tahola easily overlapping hbe.
        for j in range(img2.shape[1]):
            pixel = img2[i][j]
            if pixel == 0:
                img2[i][j] = 255
            else:
                img2[i][j] = 0


    if img1.shape != img2.shape:
         img2_resized = cv2.resize(img2, (img1.shape[1], img1.shape[0]))  #2 tar size same na hle overlapping hoi na,tai size thik kora
    else:
         img2_resized = img2

    #and operation for overlapping
    img_bwa = cv2.bitwise_and(img1, img2_resized)


    cv2_imshow(img_bwa)

    #save image
    cv2.imwrite(f'/content/drive/MyDrive/Overlapping/{p}O.png', img_bwa)

print("All binary images saved.")