# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nK8CoGMh4KroHaS1HCUCqObcfMfS1R1v
"""

import cv2
import os
from google.colab.patches import cv2_imshow
from google.colab import drive

for i in range(1, 117):


        img = cv2.imread(f'/content/{i}.png', cv2.IMREAD_GRAYSCALE)

        if img is not None:

            brighter_img = cv2.add(img, 50) #intensity 50 bariye daoya

            cv2_imshow(brighter_img)

            cv2.imwrite(f'/content/{i}A.png', brighter_img)

            print(f'Processed {i}')
        else:
            print(f'Error reading {i}')



print('Processing complete.')